/**
 * Created by FMISSER on 2017/4/6.
 * Description: vuex mutation types
 */

// 登录
export const LOGIN_SUCCEED = 'LOGIN_SUCCEED'
export const LOGIN_FAILED = 'LOGIN_FAILED'
export const LOGOUT_SUCCEED = 'LOGOUT_SUCCEED'

// 微信登录
export const WX_LOGIN_SUCCEED = 'WX_LOGIN_SUCCEED'
export const WX_LOGIN_FAILED = 'WX_LOGIN_FAILED'

// 微信登录授权
export const WX_LOGIN_OAUTH_URL_SUCCEED = 'WX_LOGIN_OAUTH_URL_SUCCEED'
export const WX_LOGIN_OAUTH_URL_FAILED = 'WX_LOGIN_OAUTH_URL_FAILED'

// 注册
export const REGISTER_SUCCEED = 'REGISTER_SUCCEED'
export const REGISTER_FAILED = 'REGISTER_FAILED'

// 游客登录
export const VISITOR_LOGIN_SUCCEED = 'VISITOR_LOGIN_SUCCEED'
export const VISITOR_LOGIN_FAILED = 'VISITOR_LOGIN_FAILED'

// 获取验证码
export const GET_CAPTCHA_SUCCEED = 'GET_CAPTCHA_SUCCEED'
export const GET_CAPTCHA_FAILED = 'GET_CAPTCHA_FAILED'

// 微信相关
export const WX_GET_OAUTH_URL_SUCCEED = 'WX_GET_OAUTH_URL'
export const WX_GET_OAUTH_URL_FAILED = 'WX_GET_OAUTH_URL_FAILED'
export const WX_GET_SUBSCRIBE_SUCCEED = 'WX_GET_SUBSCRIBE_SUCCEED'
export const WX_GET_SUBSCRIBE_FAILED = 'WX_GET_SUBSCRIBE_FAILED'

// 获取商城列表
export const GET_STORE_LIST_SUCCEED = 'GET_STORE_LIST_SUCCEED'
export const GET_STORE_LIST_FAILED = 'GET_STORE_LIST_FAILED'
// 刷新商城列表
export const REFRESH_STORE_LIST_SUCCEED = 'REFRESH_STORE_LIST_SUCCEED'
export const REFRESH_STORE_LIST_FAILED = 'REFRESH_STORE_LIST_FAILED'
// 商城详情
export const GET_STORE_ITEM_SUCCEED = 'GET_STORE_ITEM_SUCCEED'
export const GET_STORE_ITEM_FAILED = 'GET_STORE_ITEM_FAILED'
// 商城兑换
export const STORE_REVERT_SUCCEED = 'STORE_REVERT_SUCCEED'
export const STORE_REVERT_FAILED = 'STORE_REVERT_FAILED'
export const STORE_PAY_SUCCEED = 'STORE_PAY_SUCCEED'
export const STORE_PAY_FAILED = 'STORE_PAY_FAILED'

// 获取金币信息
export const GET_USER_COIN_SUCCEED = 'GET_USER_COIN_SUCCEED'
export const GET_USER_COIN_FAILED = 'GET_USER_COIN_FAILED'
// 获取用户信息
export const GET_USER_INFO_SUCCEED = 'GET_USER_INFO_SUCCEED'
export const GET_USER_INFO_FAILED = 'GET_USER_INFO_FAILED'

// 获取竞猜数据
export const GET_QUIZ_LIST_SUCCEED = 'GET_QUIZ_LIST_SUCCEED'
export const GET_QUIZ_LIST_FAILED = 'GET_QUIZ_LIST_FAILED'
export const REFRESH_QUIZ_LIST_SUCCESS = 'REFRESH_QUIZ_LIST_SUCCESS'
export const HOMEPAGE_QUIZ_BET_SUCCEED = 'HOMEPAGE_QUIZ_BET_SUCCEED'
export const HOMEPAGE_QUIZ_BET_FAILED = 'HOMEPAGE_QUIZ_BET_FAILED'
export const GET_QUIZ_DETAIL_FOR_PUSH_SUCCESS = 'GET_QUIZ_DETAIL_FOR_PUSH_SUCCESS'
export const GET_QUIZ_DETAIL_FOR_PUSH_FAILED = 'GET_QUIZ_DETAIL_FOR_PUSH_FAILED'

// 获取竞猜发布者信息
export const GET_PUBLISHER_INFO_SUCCEED = 'GET_PUBLISHER_INFO_SUCCEED'
export const GET_PUBLISHER_INFO_FAILED = 'GET_PUBLISHER_INFO_FAILED'

// 获取竞猜玩家列表
export const GET_QUIZ_PLAYERS_SUCCEED = 'GET_QUIZ_PLAYERS_SUCCEED'
export const GET_QUIZ_PLAYERS_FAILED = 'GET_QUIZ_PLAYERS_FAILED'

// 获取与我相关列表
export const GET_RELATED_LIST_SUCCEED = 'GET_RELATED_LIST_SUCCEED'
export const GET_RELATED_LIST_FAILED = 'GET_RELATED_LIST_FAILED'
export const REFRESH_RELATED_LIST_SUCCEED = 'REFRESH_RELATED_LIST_SUCCEED'
export const GET_RELATED_ITEM_FOR_PUSH_SUCCESS = 'GET_RELATED_ITEM_FOR_PUSH_SUCCESS'
export const GET_RELATED_ITEM_FOR_PUSH_FAILED = 'GET_RELATED_ITEM_FOR_PUSH_FAILED'

// 获取我的发布
export const GET_MINE_PUBLISH_SUCCEED = 'GET_MINE_PUBLISH_SUCCEED'
export const GET_MINE_PUBLISH_FAILED = 'GET_MINE_PUBLISH_FAILED'
export const REFRESH_MINE_PUBLISH_SUCCEED = 'REFRESH_MINE_PUBLISH_SUCCEED'

// 发布
export const UPLOAD_DATA_SUCCEED = 'UPLOAD_DATA_SUCCEED'
export const UPLOAD_DATA_FAILED = 'UPLOAD_DATA_FAILED'
export const ASSIGN_UPLOAD_IMAGES = 'ASSIGN_UPLOAD_IMAGES'
export const UPLOAD_USERINFO_SUCCEED = 'UPLOAD_USERINFO_SUCCEED'
export const UPLOAD_USERINFO_FAILED = 'UPLOAD_USERINFO_FAILED'

// 发布后分享
export const WX_SHARE_JS_SDK_CONF_SUCCEED = 'WX_SHARE_JS_SDK_CONF_SUCCEED'
export const WX_SHARE_JS_SDK_CONF_FAILED = 'WX_SHARE_JS_SDK_CONF_FAILED'

// 竞猜详情
export const GET_QUIZ_DETAIL_SUCCEED = 'GET_QUIZ_DETAIL_SUCCEED'
export const GET_QUIZ_DETAIL_FAILED = 'GET_QUIZ_DETAIL_FAILED'
export const QUIZ_BET_SUCCEED = 'QUIZ_BET_SUCCEED'
export const QUIZ_BET_FAILED = 'QUIZ_BET_FAILED'
export const NAV_TO_QUIZ_DETAIL = 'NAV_TO_QUIZ_DETAIL'

export const GET_HISTORY_MESSAGE_SUCCEED = 'GET_HISTORY_MESSAGE_SUCCEED'
export const GET_HISTORY_MESSAGE_FAILED = 'GET_HISTORY_MESSAGE_FAILED'

// ranking
export const GET_RANKING_SUCCEED = 'GET_RANKING_SUCCEED'
export const GET_RANKING_FAILED = 'GET_RANKING_FAILED'
export const REFRESH_RANKING_SUCCEED = 'REFRESH_RANKING_SUCCEED'

// 充值
export const GET_RECHARGE_SUCCEED = 'GET_RECHARGE_SUCCEED'
export const GET_RECHARGE_FAILED = 'GET_RECHARGE_FAILED'

// app 微信支付
export const GET_APP_RECHARGE_SUCCEED = 'GET_APP_RECHARGE_SUCCEED'
export const GET_APP_RECHARGE_FAILED = 'GET_APP_RECHARGE_FAILED'
export const GET_APP_WX_APPID_SUCCEED = 'GET_APP_WX_APPID_SUCCEED'
export const GET_APP_WX_APPID_FAILED = 'GET_APP_WX_APPID_FAILED'
export const APP_WX_PAY_SUCCEED = 'APP_WX_PAY_SUCCEED'
export const APP_WX_PAY_FAILED = 'APP_WX_PAY_FAILED'
export const APP_ALI_PAY_SUCCEED = 'APP_ALI_PAY_SUCCEED'
export const APP_ALI_PAY_FAILED = 'APP_ALI_PAY_FAILED'
export const APP_ALI_WEB_PAY_SUCCEED = 'APP_ALI_WEB_PAY_SUCCEED'
export const APP_ALI_WEB_PAY_FAILED = 'APP_ALI_WEB_PAY_FAILED'

// app 推送
export const APP_DEVICE_TOKEN_PUSH_SUCCEED = 'APP_DEVICE_TOKEN_PUSH_SUCCEED'
export const APP_DEVICE_TOKEN_PUSH_FAILED = 'APP_DEVICE_TOKEN_PUSH_FAILED'

// iap recharge
export const GET_IAP_RECHARGE_SUCCEED = 'GET_IAP_RECHARGE_SUCCEED'
export const GET_IAP_RECHARGE_FAILED = 'GET_IAP_RECHARGE_FAILED'
export const VERIFY_IAP_SUCCEED = 'VERIFY_IAP_SUCCEED'
export const VERIFY_IAP_FAILED = 'VERIFY_IAP_FAILED'

// wx 支付返回参数
export const GET_WX_JS_PAY_PARAMS_SUCCEED = 'GET_WX_JS_PAY_PARAMS_SUCCEED'
export const GET_WX_JS_PAY_PARAMS_FAILED = 'GET_WX_JS_PAY_PARAMS_FAILED'

// wx js sdk config
export const GET_WX_JS_SDK_CONFIG_SUCCEED = 'GET_WX_JS_SDK_CONFIG_SUCCEED'
export const GET_WX_JS_SDK_CONFIG_FAILED = 'GET_WX_JS_SDK_CONFIG_FAILED'

// 微信相关

// 获取微信授权URL
export const GET_WECHAT_OAUTH_URL_SUCCEED = 'GET_WECHAT_OAUTH_URL_SUCCEED'
export const GET_WECHAT_OAUTH_URL_FAILED = 'GET_WECHAT_OAUTH_URL_FAILED'

// 获取JS SDK 配置
export const GET_WECHAT_JSSDK_CONF_SUCCEED = 'GET_WECHAT_JSSDK_CONF_SUCCEED'
export const GET_WECHAT_JSSDK_CONF_FAILED = 'GET_WECHAT_JSSDK_CONF_FAILED'

// 获取JS PAY PARAMS
export const GET_WECHAT_JSPAY_PARAMS_SUCCEED = 'GET_WECHAT_JSPAY_PARAMS_SUCCEED'
export const GET_WECHAT_JSPAY_PARAMS_FAILED = 'GET_WECHAT_JSPAY_PARAMS_FAILED'

// 配置服務器地址
export const GET_SERV_ADDR_SUCCEED = 'GET_SERV_ADDR_SUCCEED'
export const GET_SERV_ADDR_FAILED = 'GET_SERV_ADDR_FAILED'

// 任务信息
export const GET_TASK_DATA_SUCCEED = 'GET_TASK_DATA_SUCCEED'
export const GET_TASK_DATA_FAILED = 'GET_TASK_DATA_FAILED'
export const GET_TASK_REWARD_SUCCEED = 'GET_TASK_REWARD_SUCCEED'
export const GET_TASK_REWARD_FAILED = 'GET_TASK_REWARD_FAILED'

// 手动开奖
export const GET_HANDERDRAW_SUCCEED = 'GET_HANDERDRAW_SUCCEED'
export const GET_HANDERDRAW_FAILED = 'GET_HANDERDRAW_FAILED'

// 举报
export const REPORT_SUCCEED = 'REPORT_SUCCEED'
export const REPORT_FAILED = 'REPORT_FAILED'

// 分享竞猜
export const SHARE_SUCCEED = 'SHARE_SUCCEED'
export const SHARE_FAILED = 'SHARE_FAILED'

